In [ ]:
# np.cumprod: cummulative product, row ,column,normal

In [2]:
import numpy as np

In [4]:
a = np.array([11,22,33,344,55])

In [5]:
a

array([ 11,  22,  33, 344,  55])

In [6]:
np.cumprod(a)

array([       11,       242,      7986,   2747184, 151095120])

In [7]:
z = np.arange(30).reshape(6,5)

In [8]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [9]:
# Row wise Cumprod

np.cumprod(z,axis=0)

array([[      0,       1,       2,       3,       4],
       [      0,       6,      14,      24,      36],
       [      0,      66,     168,     312,     504],
       [      0,    1056,    2856,    5616,    9576],
       [      0,   22176,   62832,  129168,  229824],
       [      0,  576576, 1696464, 3616704, 6664896]])

In [10]:
# Columnwise cumprod

np.cumprod(z,axis=1)

array([[       0,        0,        0,        0,        0],
       [       5,       30,      210,     1680,    15120],
       [      10,      110,     1320,    17160,   240240],
       [      15,      240,     4080,    73440,  1395360],
       [      20,      420,     9240,   212520,  5100480],
       [      25,      650,    17550,   491400, 14250600]])