In [2]:
# find out min(),max() of array columnwise, rowwise
# Differnce between ravel & flattern?

import numpy as np

In [5]:
b = np.array([[23,10,34,78]])


In [6]:
b

array([[23, 10, 34, 78]])

In [7]:
b.min()

10

In [8]:
b.max()

78

In [9]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a.min()

1

In [12]:
a.max()

6

In [13]:
# Row wise min value
a.min(axis=1)

array([1, 4])

In [14]:
# Column wise value

a.max(axis=0)

array([4, 5, 6])

In [ ]:
# The flatten() function returns a copy of the array, while the ravel() function
# returns a view of the original array whenever possible