In [ ]:
# np.substract()
# np.divide()
# np.multiply()
#np.power()
#np.floor_divide()
#np.mod()

In [1]:
import numpy as np

In [2]:
a = np.array([[34,89],[23,67]])

In [3]:
a

array([[34, 89],
       [23, 67]])

In [5]:
z = np.array([[23,10],[2,58]])

In [6]:
z

array([[23, 10],
       [ 2, 58]])

In [9]:
np.subtract(a,z)

array([[11, 79],
       [21,  9]])

In [11]:
np.multiply(a,z)

array([[ 782,  890],
       [  46, 3886]])

In [12]:
np.divide(a,z)

array([[ 1.47826087,  8.9       ],
       [11.5       ,  1.15517241]])

In [14]:
np.mod(a,z)

array([[11,  9],
       [ 1,  9]])

In [15]:
np.power(a,2)

array([[1156, 7921],
       [ 529, 4489]])

In [16]:
np.floor_divide(a,z)

array([[ 1,  8],
       [11,  1]])